/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regressao2;

/**
 *
 * @author lefoly
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLalgoritmo = new javax.swing.JLabel();
        jLdadosAnt = new javax.swing.JLabel();
        jLdadosNovos = new javax.swing.JLabel();
        jBtreinar = new javax.swing.JButton();
        jBgerarPrevisao = new javax.swing.JButton();
        jCBalgoritmo = new javax.swing.JComboBox<>();
        jTdadosAnt = new javax.swing.JTextField();
        jTdadosNovos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLalgoritmo.setText("Algoritmo");

        jLdadosAnt.setText("Dados Antigos");

        jLdadosNovos.setText("Dados Novos");

        jBtreinar.setText("1 - Treinar");
        jBtreinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtreinarActionPerformed(evt);
            }
        });

        jBgerarPrevisao.setText("2 - Gerar Previsão");
        jBgerarPrevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgerarPrevisaoActionPerformed(evt);
            }
        });

        jCBalgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IBK" }));

        jTdadosAnt.setText("/home/lefoly/leitoresTreinamento.csv");

        jTdadosNovos.setText("/home/lefoly/leitoresNovos.csv");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLdadosAnt)
                                    .addComponent(jLalgoritmo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBalgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTdadosAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLdadosNovos)
                                .addGap(19, 19, 19)
                                .addComponent(jTdadosNovos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jBtreinar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jBgerarPrevisao)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLalgoritmo)
                    .addComponent(jCBalgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdadosAnt)
                    .addComponent(jTdadosAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdadosNovos)
                    .addComponent(jTdadosNovos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtreinar)
                    .addComponent(jBgerarPrevisao))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtreinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtreinarActionPerformed
              // TODO add your handling code here:
        //lê o caminho da base antiga do campo de texto correspondente
        arquivoBaseAntiga = jTdadosAnt.getText();    
        
        //inverte a \ para / do caminho do arquivo
        arquivoBaseAntiga =arquivoBaseAntiga.replace("\\", "/");

        //executa o método treinar do classificador ibk
        ibk.treinar(arquivoBaseAntiga); 
    }//GEN-LAST:event_jBtreinarActionPerformed

    private void jBgerarPrevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgerarPrevisaoActionPerformed
               //lê o caminho da base nova do campo de texto correspondente
        arquivoBaseNova = jTdadosNovos.getText();
        
        //inverte a \ para / do caminho do arquivo
        arquivoBaseNova =arquivoBaseNova.replace("\\", "/");
        
        //executa o método gravarArquivo do classificador ibk
        ibk.gravarArquivo(arquivoBaseNova);
        
    }//GEN-LAST:event_jBgerarPrevisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

        //cria os atributos para receberem os caminhos das bases
    String arquivoBaseAntiga = "";
    
    String arquivoBaseNova = "";
    
    //cria o objeto ibk que será uma instancia da classe ModoIBK
    ModoIBK ibk = new ModoIBK();
    
    private javax.swing.JTextField jTextField2;
    // End of variables declaration    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBgerarPrevisao;
    private javax.swing.JButton jBtreinar;
    private javax.swing.JComboBox<String> jCBalgoritmo;
    private javax.swing.JLabel jLalgoritmo;
    private javax.swing.JLabel jLdadosAnt;
    private javax.swing.JLabel jLdadosNovos;
    private javax.swing.JTextField jTdadosAnt;
    private javax.swing.JTextField jTdadosNovos;
    // End of variables declaration//GEN-END:variables
}
